export interface Book {
  id: number;
  title: string;
  author: string;
  price: number;
  category: string;
  cover: string;
  description: string;
}

export const categories = [
  "جميع الكتب",
  "روايات",
  "تطوير الذات",
  "تاريخ",
  "أدب عربي",
  "علوم",
  "أطفال",
];

export const books: Book[] = [
  {
    id: 1,
    title: "الأب الغني والأب الفقير",
    author: "روبرت كيوساكي",
    price: 50,
    category: "تطوير الذات",
    cover: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/WhatsApp%20Image%202026-05-08%20at%2023.01.23-jKS3Een9DuKu0MY2lZP60WJ8borkb4.jpeg",
    description: "ما يعلمه الأثرياء لأبنائهم ولا يعلمه الفقراء وأبناء الطبقة الوسطى",
  },
  {
    id: 2,
    title: "عقدك النفسية سجنك الأبدي",
    author: "د. يوسف الحسني",
    price: 50,
    category: "تطوير الذات",
    cover: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/WhatsApp%20Image%202026-05-08%20at%2023.01.21-mnflRkE1W8ujZI9zoctutLhQ1DAqX3.jpeg",
    description: "كتاب في علم النفس يساعدك على فهم عقدك النفسية والتحرر منها",
  },
  {
    id: 3,
    title: "متعة أن تكون في العشرين",
    author: "علا ديوب",
    price: 50,
    category: "تطوير الذات",
    cover: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/WhatsApp%20Image%202026-05-08%20at%2023.01.17-M0nwxT6cHNB46bhpdGvsZ2AfejjtIU.jpeg",
    description: "استمتع بشبابك وابن أسساً قوية بقية حياتك",
  },
  {
    id: 4,
    title: "متعة أن تكون في الثلاثين",
    author: "علا ديوب",
    price: 50,
    category: "تطوير الذات",
    cover: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/WhatsApp%20Image%202026-05-08%20at%2023.01.16%20%281%29-8dSbGCCunkwQN2r99GzZkctaDWSZMc.jpeg",
    description: "كيف تستمتع بالحياة وتواجه التحديات الكبرى في ثلاثينياتك",
  },
  {
    id: 5,
    title: "نظرية الفستق 2",
    author: "فهد عامر الأحمدي",
    price: 45,
    category: "تطوير الذات",
    cover: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/WhatsApp%20Image%202026-05-08%20at%2023.01.16-Qi9wS0OFZiqk8QcQfT2dYg46AtbmIr.jpeg",
    description: "كتاب في تغيير طريقة تفكيرك وحكمك على الأشياء",
  },
  {
    id: 6,
    title: "جلسات نفسية",
    author: "د. محمد إبراهيم",
    price: 53,
    category: "تطوير الذات",
    cover: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/WhatsApp%20Image%202026-05-08%20at%2023.01.21%20%282%29-71oHIS6sWTWgP3zhUIJQJum1OlhR8b.jpeg",
    description: "حتى تصل إلى السكينة النفسية",
  },
  {
    id: 7,
    title: "خوف",
    author: "أسامة المسلم",
    price: 60,
    category: "روايات",
    cover: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/WhatsApp%20Image%202026-05-08%20at%2023.01.21%20%281%29-tKl5TrUdDeEmjM1SkUA5rkML2dGlmA.jpeg",
    description: "رواية رعب وتشويق مثيرة",
  },
  {
    id: 8,
    title: "أبابيل",
    author: "أحمد آل حمدان",
    price: 60,
    category: "روايات",
    cover: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/WhatsApp%20Image%202026-05-08%20at%2023.01.20%20%282%29-mFsWLjtExMnYGCDdVhDbHOxYBSsdhU.jpeg",
    description: "الحب هو التوأم اللطيف للموت",
  },
  {
    id: 9,
    title: "السجيل",
    author: "أحمد آل حمدان",
    price: 60,
    category: "روايات",
    cover: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/WhatsApp%20Image%202026-05-08%20at%2023.01.20%20%283%29-jsCYWrpD2kBfMi8m6OZTLE8L5LxP8I.jpeg",
    description: "عاصف سليل الطين والنار",
  },
  {
    id: 10,
    title: "أذن",
    author: "أحمد آل حمدان",
    price: 58,
    category: "روايات",
    cover: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/WhatsApp%20Image%202026-05-08%20at%2023.01.20-miH6H9UzDM75poh3uRKl7YZFUK8dnW.jpeg",
    description: "ابن ذئبة الوادي - رواية ملحمية",
  },
  {
    id: 11,
    title: "أوراق شمعون المصري",
    author: "أسامة عبد الرؤوف الشاذلي",
    price: 65,
    category: "روايات",
    cover: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/WhatsApp%20Image%202026-05-08%20at%2023.01.20%20%281%29-kIphGUKuiNs54MwjDOGoG03GDxAFXN.jpeg",
    description: "رواية تاريخية مشوقة",
  },
  {
    id: 12,
    title: "عداء الطائرة الورقية",
    author: "خالد حسيني",
    price: 65,
    category: "روايات",
    cover: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/WhatsApp%20Image%202026-05-08%20at%2023.01.22%20%284%29-oCEkCDjhNXMF2tA2vkHbFVMZ5BcoZ0.jpeg",
    description: "رواية مؤثرة عن الصداقة والخيانة والفداء",
  },
  {
    id: 13,
    title: "الجريمة والعقاب الجزء 1و2",
    author: "دوستويفسكي",
    price: 110,
    category: "روايات",
    cover: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/WhatsApp%20Image%202026-05-08%20at%2023.01.22%20%283%29-IkeY06LLX9nXmcWBJ0lpplV9qGzps7.jpeg",
    description: "رواية كلاسيكية عن الضمير والعدالة",
  },
  {
    id: 14,
    title: "الليالي البيضاء",
    author: "دوستويفسكي",
    price: 40,
    category: "روايات",
    cover: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/WhatsApp%20Image%202026-05-08%20at%2023.01.17%20%281%29-OFpupoGAlV6jlXpTIf3wUDSBQt1RRJ.jpeg",
    description: "قصة رومانسية قصيرة من الأدب الروسي",
  },
  {
    id: 15,
    title: "1984",
    author: "جورج أورويل",
    price: 50,
    category: "روايات",
    cover: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/WhatsApp%20Image%202026-05-08%20at%2023.01.22%20%281%29-wC1EdLnnPkl8FlZeZOXlolav7RN4O2.jpeg",
    description: "رواية ديستوبية عن الرقابة والشمولية",
  },
  {
    id: 16,
    title: "مزرعة الحيوان",
    author: "جورج أورويل",
    price: 38,
    category: "روايات",
    cover: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/WhatsApp%20Image%202026-05-08%20at%2023.01.22%20%282%29-cJTrxhOSBkaiu3LlYuzlhxt72zA3wv.jpeg",
    description: "حين يتساوى الإنسان مع الحيوان في السلوك",
  },
  {
    id: 17,
    title: "الأمير",
    author: "نيقولا مكيافيلي",
    price: 42,
    category: "تاريخ",
    cover: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/WhatsApp%20Image%202026-05-08%20at%2023.01.22-Td5GbPDP6LNpBZsfA6YkLDkqZLXTiB.jpeg",
    description: "كتاب في فن السياسة والحكم",
  },
  {
    id: 18,
    title: "كفاحي",
    author: "أدولف هتلر",
    price: 35,
    category: "تاريخ",
    cover: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/WhatsApp%20Image%202026-05-08%20at%2023.01.21%20%283%29-D4CKe0eaR9PH5Sj0bkRXGtFnHgVLBk.jpeg",
    description: "السيرة الذاتية والأفكار السياسية",
  },
  {
    id: 19,
    title: "الجساسة",
    author: "أحمد آل حمدان",
    price: 35,
    category: "تاريخ",
    cover: "https://m.media-amazon.com/images/I/618oXzR3jzL._AC_UF894,1000_QL80_.jpg",
    description: "رواية تاريخية مشوقة",
  }, {
    id: 20,
    title: "والذين معه",
    author: "أدهم شرقاوي",
    price: 35,
    category: "أدب عربي",
    cover: "https://covers.openlibrary.org/b/title/والذين%20معه-L.jpg",
    description: "رواية أدبية",
  },
  {
    id: 21,
    title: "اليوم أجمل",
    author: "علي السلماني",
    price: 35,
    category: "أدب عربي",
    cover: "https://covers.openlibrary.org/b/title/اليوم%20أجمل-L.jpg",
    description: "رواية اجتماعية",
  },
  {
    id: 22,
    title: "نظرية الفستق",
    author: "فهد عامر الأحمدي",
    price: 45,
    category: "تطوير الذات",
    cover: "https://covers.openlibrary.org/b/title/نظرية%20الفستق-L.jpg",
    description: "تغيير طريقة التفكير",
  },
  {
    id: 23,
    title: "جومانا",
    author: "أحمد آل حمدان",
    price: 35,
    category: "روايات",
    cover: "https://covers.openlibrary.org/b/title/جومانا-L.jpg",
    description: "رواية رومانسية",
  },
  {
    id: 24,
    title: "حتى لا تذهب للمأذون مرتين",
    author: "د. دعاء الرشيدي",
    price: 30,
    category: "أدب عربي",
    cover: "https://covers.openlibrary.org/b/title/حتى%20لا%20تذهب%20للمأذون%20مرتين-L.jpg",
    description: "كتاب اجتماعي",
  },
  {
    id: 25,
    title: "فتاة الياقة الزرقاء",
    author: "عمرو عبد الحميد",
    price: 35,
    category: "روايات",
    cover: "https://covers.openlibrary.org/b/title/فتاة%20الياقة%20الزرقاء-L.jpg",
    description: "رواية خيالية",
  },
  {
    id: 26,
    title: "أمارليتا",
    author: "عمرو عبد الحميد",
    price: 35,
    category: "روايات",
    cover: "https://covers.openlibrary.org/b/title/أمارليتا-L.jpg",
    description: "جزء من عالم روايات خيالية",
  },
  {
    id: 27,
    title: "آخر أسرار الهيكل",
    author: "بول سوسمان",
    price: 35,
    category: "روايات",
    cover: "https://covers.openlibrary.org/b/title/آخر%20أسرار%20الهيكل-L.jpg",
    description: "رواية غموض تاريخية",
  },
  {
    id: 28,
    title: "الجثة",
    author: "",
    price: 30,
    category: "رعب",
    cover: "https://covers.openlibrary.org/b/title/الجثة-L.jpg",
    description: "رواية رعب",
  },
  {
    id: 29,
    title: "005",
    author: "شهد قربان",
    price: 30,
    category: "روايات",
    cover: "https://covers.openlibrary.org/b/title/005-L.jpg",
    description: "رواية غامضة",
  },
  {
    id: 30,
    title: "اكتب حتى لا يأكلني الشيطان",
    author: "مريم الكعبي",
    price: 30,
    category: "تطوير الذات",
    cover: "https://covers.openlibrary.org/b/title/اكتب%20حتى%20لا%20يأكلني%20الشيطان-L.jpg",
    description: "تطوير الذات والوعي",
  },
  {
    id: 31,
    title: "أريس",
    author: "",
    price: 35,
    category: "روايات",
    cover: "https://covers.openlibrary.org/b/title/أريس-L.jpg",
    description: "رواية خيالية",
  },
  {
    id: 32,
    title: "أريس 2",
    author: "",
    price: 35,
    category: "روايات",
    cover: "https://covers.openlibrary.org/b/title/أريس%202-L.jpg",
    description: "الجزء الثاني",
  },
  {
    id: 33,
    title: "7 مراحل لتصبح كاتباً",
    author: "",
    price: 30,
    category: "تطوير الذات",
    cover: "https://covers.openlibrary.org/b/title/7%20مراحل%20لتصبح%20كاتباً-L.jpg",
    description: "تطوير مهارات الكتابة",
  },
  {
    id: 34,
    title: "إستراتيجية المحيط الأزرق",
    author: "Blue Ocean Strategy",
    price: 45,
    category: "تطوير الذات",
    cover: "https://covers.openlibrary.org/b/title/Blue%20Ocean%20Strategy-L.jpg",
    description: "استراتيجية الأعمال",
  },
  {
    id: 35,
    title: "الخيميائي",
    author: "باولو كويلو",
    price: 40,
    category: "روايات",
    cover: "https://covers.openlibrary.org/b/title/The%20Alchemist-L.jpg",
    description: "رحلة تحقيق الأحلام",
  },
  {
    id: 36,
    title: "Atomic Habits",
    author: "James Clear",
    price: 45,
    category: "تطوير الذات",
    cover: "https://covers.openlibrary.org/b/title/Atomic%20Habits-L.jpg",
    description: "بناء العادات الصغيرة",
  },
  {
    id: 37,
    title: "1Q84",
    author: "هاروكي موراكامي",
    price: 50,
    category: "روايات",
    cover: "https://covers.openlibrary.org/b/title/1Q84-L.jpg",
    description: "رواية خيالية فلسفية",
  },
  {
    id: 38,
    title: "الغريب",
    author: "ألبير كامو",
    price: 35,
    category: "روايات",
    cover: "https://covers.openlibrary.org/b/title/The%20Stranger-L.jpg",
    description: "رواية فلسفية",
  },
  {
    id: 39,
    title: "Reminders of Him",
    author: "Colleen Hoover",
    price: 45,
    category: "روايات",
    cover: "https://covers.openlibrary.org/b/title/Reminders%20of%20Him-L.jpg",
    description: "رواية رومانسية مؤثرة",
  },
  {
    id: 40,
    title: "The Housemaid’s Secret",
    author: "Freida McFadden",
    price: 45,
    category: "روايات",
    cover: "https://covers.openlibrary.org/b/title/The%20Housemaid's%20Secret-L.jpg",
    description: "رواية إثارة وغموض",
  },
];
